spring:
  application:
    name: FoodNow
  datasource:
    url: jdbc:postgresql://localhost:5432/food_now_api
    username: postgres
    password: dev
    driver-class-name: org.postgresql.Driver
    hikari:
#      quantidade máxima de conexão da pool
      maximum-pool-size: 5
#      quantidade mínima de conexão da pool
      minimum-idle: 3
#      tempo de timeout para desconectar pool em idle (ms)
      idle-timeout: 10000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
#    passando a localização do db/migration e db/testdata para executar os scripts
    locations: classpath:db/migration,classpath:db/testdata
#      javax:            Gera o ddl de criação das tabelas pelo mapeamento do JPA (Não executa o código sql)
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: src/main/resources/ddl.sql

#    generate-ddl: true
#    hibernate:
#      ddl-auto: create