spring:
  application:
    name: FoodNow
  datasource:
    url: jdbc:postgresql://localhost:5432/food_now_api
    username: postgres
    password: dev
    driver-class-name: org.postgresql.Driver
    hikari:
#      quantidade máxima de conexão da pool
      maximum-pool-size: 5
#      quantidade mínima de conexão da pool
      minimum-idle: 3
#      tempo de timeout para desconectar pool em idle (ms)
      idle-timeout: 10000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create