create table group_ (
    id bigint generated by default as identity,
    name varchar(60) not null,
    primary key (id)
);

create table group_role (
    group_id bigint not null,
    role_id bigint not null
);

create table payment_method (
    id bigint generated by default as identity,
    description varchar(50) not null,
    primary key (id)
);

create table product (
     active boolean not null, price numeric(38,2) not null,
     id bigint generated by default as identity,
     restaurant_id bigint not null,
     description varchar(150) not null,
     name varchar(80) not null,
     primary key (id)
);

create table restaurant (
    id bigint generated by default as identity,
    delivery_fee numeric(38,2) not null,
    address_city_id bigint,
    created_at timestamp(6) not null,
    cuisine_id bigint not null,
    updated_at timestamp(6),
    name varchar(30) not null,
    address_number varchar(50),
    address_street varchar(150),
    address_zipcode varchar(11),
    primary key (id)
);

create table restaurant_payment_method (
   payment_method_id bigint not null,
   restaurant_id bigint not null
);

create table role (
    id bigint generated by default as identity,
    description varchar(150) not null,
    name varchar(80) not null,
    primary key (id)
);

create table user_ (
    created_at timestamp(6),
    id bigint generated by default as identity,
    email varchar(255),
    name varchar(255),
    password varchar(50),
    primary key (id)
);
create table user_group (
    group_id bigint not null,
    user_id bigint not null
);

-- CONSTRAINS
alter table if exists group_role add constraint fk_role_id_group_role foreign key (role_id) references role;
alter table if exists group_role add constraint fK_group_id_group_role foreign key (group_id) references group_;
alter table if exists product add constraint fk_restaurant_id_product foreign key (restaurant_id) references restaurant;
alter table if exists restaurant add constraint fk_address_city_id_restaurant foreign key (address_city_id) references city;
alter table if exists restaurant add constraint fk_cuisine_id_restaurant foreign key (cuisine_id) references cuisine;
alter table if exists restaurant_payment_method add constraint fk_payment_method_id_restaurant_payment_method foreign key (payment_method_id) references payment_method;
alter table if exists restaurant_payment_method add constraint fk_restaurant_id_restaurant_payment_method foreign key (restaurant_id) references restaurant;
alter table if exists user_group add constraint fk_group_id_user_group foreign key (group_id) references group_;
alter table if exists user_group add constraint fk_user_id_user_group foreign key (user_id) references user_;

-- SET TIMEZONE
SET TIMEZONE TO 'UTC';
